/**
 * Comprehensive fallback list of popular USDT spot pairs.
 * Used when the dynamic exchange listing is still loading, errored, or rate-limited.
 * Always available (no network) so the dropdown is never empty.
 *
 * Note: When the live API is reachable, this list is fully replaced by the
 * exchange's full symbol list (hundreds of pairs).
 */
const RAW_POPULAR_USDT_PAIRS: { symbol: string; base: string; quote: string }[] = [
  // Top 20 by volume
  { symbol: 'BTCUSDT', base: 'BTC', quote: 'USDT' },
  { symbol: 'ETHUSDT', base: 'ETH', quote: 'USDT' },
  { symbol: 'SOLUSDT', base: 'SOL', quote: 'USDT' },
  { symbol: 'BNBUSDT', base: 'BNB', quote: 'USDT' },
  { symbol: 'XRPUSDT', base: 'XRP', quote: 'USDT' },
  { symbol: 'DOGEUSDT', base: 'DOGE', quote: 'USDT' },
  { symbol: 'ADAUSDT', base: 'ADA', quote: 'USDT' },
  { symbol: 'TRXUSDT', base: 'TRX', quote: 'USDT' },
  { symbol: 'AVAXUSDT', base: 'AVAX', quote: 'USDT' },
  { symbol: 'TONUSDT', base: 'TON', quote: 'USDT' },
  { symbol: 'LINKUSDT', base: 'LINK', quote: 'USDT' },
  { symbol: 'MATICUSDT', base: 'MATIC', quote: 'USDT' },
  { symbol: 'DOTUSDT', base: 'DOT', quote: 'USDT' },
  { symbol: 'LTCUSDT', base: 'LTC', quote: 'USDT' },
  { symbol: 'BCHUSDT', base: 'BCH', quote: 'USDT' },
  { symbol: 'NEARUSDT', base: 'NEAR', quote: 'USDT' },
  { symbol: 'ATOMUSDT', base: 'ATOM', quote: 'USDT' },
  { symbol: 'APTUSDT', base: 'APT', quote: 'USDT' },
  { symbol: 'OPUSDT', base: 'OP', quote: 'USDT' },
  { symbol: 'ARBUSDT', base: 'ARB', quote: 'USDT' },
  // DeFi & L2
  { symbol: 'INJUSDT', base: 'INJ', quote: 'USDT' },
  { symbol: 'SUIUSDT', base: 'SUI', quote: 'USDT' },
  { symbol: 'SEIUSDT', base: 'SEI', quote: 'USDT' },
  { symbol: 'TIAUSDT', base: 'TIA', quote: 'USDT' },
  { symbol: 'STXUSDT', base: 'STX', quote: 'USDT' },
  { symbol: 'IMXUSDT', base: 'IMX', quote: 'USDT' },
  { symbol: 'MNTUSDT', base: 'MNT', quote: 'USDT' },
  { symbol: 'RNDRUSDT', base: 'RNDR', quote: 'USDT' },
  { symbol: 'FETUSDT', base: 'FET', quote: 'USDT' },
  { symbol: 'RUNEUSDT', base: 'RUNE', quote: 'USDT' },
  { symbol: 'AAVEUSDT', base: 'AAVE', quote: 'USDT' },
  { symbol: 'UNIUSDT', base: 'UNI', quote: 'USDT' },
  { symbol: 'MKRUSDT', base: 'MKR', quote: 'USDT' },
  { symbol: 'COMPUSDT', base: 'COMP', quote: 'USDT' },
  { symbol: 'CRVUSDT', base: 'CRV', quote: 'USDT' },
  { symbol: 'SNXUSDT', base: 'SNX', quote: 'USDT' },
  { symbol: 'LDOUSDT', base: 'LDO', quote: 'USDT' },
  { symbol: 'METHUSDT', base: 'METH', quote: 'USDT' },
  { symbol: 'RPLUSDT', base: 'RPL', quote: 'USDT' },
  { symbol: 'DYDXUSDT', base: 'DYDX', quote: 'USDT' },
  { symbol: 'GMXUSDT', base: 'GMX', quote: 'USDT' },
  // Meme coins
  { symbol: 'SHIBUSDT', base: 'SHIB', quote: 'USDT' },
  { symbol: 'PEPEUSDT', base: 'PEPE', quote: 'USDT' },
  { symbol: 'WIFUSDT', base: 'WIF', quote: 'USDT' },
  { symbol: 'BONKUSDT', base: 'BONK', quote: 'USDT' },
  { symbol: 'FLOKIUSDT', base: 'FLOKI', quote: 'USDT' },
  { symbol: 'MEMEUSDT', base: 'MEME', quote: 'USDT' },
  { symbol: 'BABYDOGEUSDT', base: 'BABYDOGE', quote: 'USDT' },
  { symbol: '1000SATSUSDT', base: '1000SATS', quote: 'USDT' },
  // AI & Data
  { symbol: 'OCEANUSDT', base: 'OCEAN', quote: 'USDT' },
  { symbol: 'TAOUSDT', base: 'TAO', quote: 'USDT' },
  { symbol: 'WLDUSDT', base: 'WLD', quote: 'USDT' },
  { symbol: 'AGIXUSDT', base: 'AGIX', quote: 'USDT' },
  // Privacy
  { symbol: 'XMRUSDT', base: 'XMR', quote: 'USDT' },
  { symbol: 'ZECUSDT', base: 'ZEC', quote: 'USDT' },
  { symbol: 'DASHUSDT', base: 'DASH', quote: 'USDT' },
  // Payment
  { symbol: 'XLMUSDT', base: 'XLM', quote: 'USDT' },
  { symbol: 'NANOUSDT', base: 'NANO', quote: 'USDT' },
  // Storage & Web3
  { symbol: 'FILUSDT', base: 'FIL', quote: 'USDT' },
  { symbol: 'ARUSDT', base: 'AR', quote: 'USDT' },
  { symbol: 'ICPUSDT', base: 'ICP', quote: 'USDT' },
  { symbol: 'HBARUSDT', base: 'HBAR', quote: 'USDT' },
  { symbol: 'VETUSDT', base: 'VET', quote: 'USDT' },
  { symbol: 'FTMUSDT', base: 'FTM', quote: 'USDT' },
  { symbol: 'ALGOUSDT', base: 'ALGO', quote: 'USDT' },
  { symbol: 'EGLDUSDT', base: 'EGLD', quote: 'USDT' },
  { symbol: 'FLOWUSDT', base: 'FLOW', quote: 'USDT' },
  { symbol: 'CHZUSDT', base: 'CHZ', quote: 'USDT' },
  { symbol: 'SANDUSDT', base: 'SAND', quote: 'USDT' },
  { symbol: 'MANAUSDT', base: 'MANA', quote: 'USDT' },
  { symbol: 'AXSUSDT', base: 'AXS', quote: 'USDT' },
  { symbol: 'GALAUSDT', base: 'GALA', quote: 'USDT' },
  { symbol: 'ENJUSDT', base: 'ENJ', quote: 'USDT' },
  { symbol: 'APEUSDT', base: 'APE', quote: 'USDT' },
  { symbol: 'BLURUSDT', base: 'BLUR', quote: 'USDT' },
  // Oracles & Infra
  { symbol: 'GRTUSDT', base: 'GRT', quote: 'USDT' },
  { symbol: 'BANDUSDT', base: 'BAND', quote: 'USDT' },
  // Other majors
  { symbol: 'ETCUSDT', base: 'ETC', quote: 'USDT' },
  { symbol: 'BSVUSDT', base: 'BSV', quote: 'USDT' },
  { symbol: 'EOSUSDT', base: 'EOS', quote: 'USDT' },
  { symbol: 'NEOUSDT', base: 'NEO', quote: 'USDT' },
  { symbol: 'IOTAUSDT', base: 'IOTA', quote: 'USDT' },
  { symbol: 'XTZUSDT', base: 'XTZ', quote: 'USDT' },
  { symbol: 'THETAUSDT', base: 'THETA', quote: 'USDT' },
  { symbol: 'KSMUSDT', base: 'KSM', quote: 'USDT' },
  { symbol: 'ZILUSDT', base: 'ZIL', quote: 'USDT' },
  { symbol: 'BATUSDT', base: 'BAT', quote: 'USDT' },
  { symbol: 'ZRXUSDT', base: 'ZRX', quote: 'USDT' },
  { symbol: 'OMGUSDT', base: 'OMG', quote: 'USDT' },
  { symbol: 'QTUMUSDT', base: 'QTUM', quote: 'USDT' },
  { symbol: 'LRCUSDT', base: 'LRC', quote: 'USDT' },
  { symbol: 'ANKRUSDT', base: 'ANKR', quote: 'USDT' },
  { symbol: 'HOTUSDT', base: 'HOT', quote: 'USDT' },
  { symbol: 'CELOUSDT', base: 'CELO', quote: 'USDT' },
  { symbol: 'KAVAUSDT', base: 'KAVA', quote: 'USDT' },
  { symbol: 'ROSEUSDT', base: 'ROSE', quote: 'USDT' },
  { symbol: 'JSTUSDT', base: 'JST', quote: 'USDT' },
  { symbol: 'SUNUSDT', base: 'SUN', quote: 'USDT' },
  // Newer / trending
  { symbol: 'JUPUSDT', base: 'JUP', quote: 'USDT' },
  { symbol: 'PYTHUSDT', base: 'PYTH', quote: 'USDT' },
  { symbol: 'JTOUSDT', base: 'JTO', quote: 'USDT' },
  { symbol: 'STRKUSDT', base: 'STRK', quote: 'USDT' },
  { symbol: 'ALTUSDT', base: 'ALT', quote: 'USDT' },
  { symbol: 'MANTAUSDT', base: 'MANTA', quote: 'USDT' },
  { symbol: 'PIXELUSDT', base: 'PIXEL', quote: 'USDT' },
  { symbol: 'PORTALUSDT', base: 'PORTAL', quote: 'USDT' },
  { symbol: 'AEVOUSDT', base: 'AEVO', quote: 'USDT' },
  { symbol: 'ETHFIUSDT', base: 'ETHFI', quote: 'USDT' },
  { symbol: 'BOMEUSDT', base: 'BOME', quote: 'USDT' },
  { symbol: 'ENAUSDT', base: 'ENA', quote: 'USDT' },
  { symbol: 'ONDOUSDT', base: 'ONDO', quote: 'USDT' },
  { symbol: 'WUSDT', base: 'W', quote: 'USDT' },
  { symbol: 'TNSRUSDT', base: 'TNSR', quote: 'USDT' },
  { symbol: 'SAGAUSDT', base: 'SAGA', quote: 'USDT' },
  { symbol: 'REZUSDT', base: 'REZ', quote: 'USDT' },
  { symbol: 'IOUSDT', base: 'IO', quote: 'USDT' },
  { symbol: 'ZROUSDT', base: 'ZRO', quote: 'USDT' },
  { symbol: 'LISTAUSDT', base: 'LISTA', quote: 'USDT' },
  { symbol: 'BANANAUSDT', base: 'BANANA', quote: 'USDT' },
  { symbol: 'NOTUSDT', base: 'NOT', quote: 'USDT' },
  { symbol: 'DOGSUSDT', base: 'DOGS', quote: 'USDT' },
  { symbol: 'HMSTRUSDT', base: 'HMSTR', quote: 'USDT' },
  { symbol: 'EIGENUSDT', base: 'EIGEN', quote: 'USDT' },
  { symbol: 'SCRUSDT', base: 'SCR', quote: 'USDT' },
  { symbol: 'BBUSDT', base: 'BB', quote: 'USDT' },
  { symbol: 'CATIUSDT', base: 'CATI', quote: 'USDT' },
  { symbol: 'NEIROUSDT', base: 'NEIRO', quote: 'USDT' },
  { symbol: 'TURBOUSDT', base: 'TURBO', quote: 'USDT' },
  { symbol: 'BIOUSDT', base: 'BIO', quote: 'USDT' },
  { symbol: 'GUSDT', base: 'G', quote: 'USDT' },
];

// Dedupe at module load (preserves first occurrence / source order)
const _seen = new Set<string>();
export const POPULAR_USDT_PAIRS: { symbol: string; base: string; quote: string }[] = RAW_POPULAR_USDT_PAIRS.filter(
  (p) => (_seen.has(p.symbol) ? false : (_seen.add(p.symbol), true))
);

export const POPULAR_TRENDING = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'BNBUSDT', 'XRPUSDT'];
